apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: nginx:1.14.2 
        ports:
        - containerPort: 80 