name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    name: Lint Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run ./...

  Test_app:
    name: Test Go Application
    runs-on: ubuntu-latest
    needs: Lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v

  Sonar_scan:
    name: Scan Go Application
    runs-on: ubuntu-latest
    needs: Test_app

    steps:
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v3.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
       args: >
         -Dsonar.organization=devops-projectslabs
         -Dsonar.projectKey=devops-projectslabs_go-web-app
         
  Build_app:
    name: Build Go Application
    runs-on: ubuntu-latest
    needs: Test_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: go mod download

      - name: Build Application
        run: |
          go build
          ls -l

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: Build_app

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: testingkyaw/go-web-app:${{ github.sha }}

  docker-ecr:
    name: Docker Build and Push-ECR
    runs-on: ubuntu-latest
    needs: Build_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t 403922132857.dkr.ecr.us-east-1.amazonaws.com/go-web-app:${{ github.run_id }} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: push image to ECR
        run: docker push 403922132857.dkr.ecr.us-east-1.amazonaws.com/go-web-app:${{ github.run_id }}

  Update-helm-cherts:
    runs-on: ubuntu-latest
    needs: docker-ecr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' go-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "kyawzawaung321@gmail.com"
        git config --global user.name "kyawzawaungdevops"
        git add go-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"



